var User = require ('../model/user');
var Item = require ('../model/item');

var mongoose = require('mongoose');
mongoose.connect('localhost:27017/sample')  


var users = [
	new User({
	  username: "kellian",
	  password: "ketchupcoffee55",
	  avatar: "../images/kellian.png"
	})
];

var items = [
	new Item({
		author: "kellian",
		title: "Oshawott Kaiyodo Bottle Cap Figure",
		image: "oshawott-kaiyodo-bottlecap.jpg",
		character: "Oshawott",
		category: "Bottle Cap",
		content: "",
		company: "Kaiyodo",
		series: "Bottle Cap Figures",
		releaseYear: 2010,
		priceUSD: 0,
		priceYen: 0,
		tag: ['bottle-cap','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tepig Kaiyodo Bottle Cap Figure",
		image: "tepig-kaiyodo-bottlecap.jpg",
		character: "Tepig",
		category: "Bottle Cap",
		content: "",
		company: "Kaiyodo",
		series: "Bottle Cap Figures",
		releaseYear: 2010,
		priceUSD: 0,
		priceYen: 0,
		tag: ['bottle-cap','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Snivy Kaiyodo Bottle Cap Figure",
		image: "snivy-kaiyodo-bottlecap.jpg",
		character: "Snivy",
		category: "Bottle Cap",
		content: "",
		company: "Kaiyodo",
		series: "Bottle Cap Figures",
		releaseYear: 2010,
		priceUSD: 0,
		priceYen: 0,
		tag: ['bottle-cap','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Charizard",
		image: "CharizardNextQuest1Spin.png",
		character: "Charizard",
		category: "Trading Figure Game",
		content: "Charizard might not move around the board too quickly with only 1 MP, but its Fire Spin attack makes it a tough Pokémon to beat! Each time Charizard gets Fire Spin, you keep spinning: 50, 100, 150, 200... there's no limit on how much damage Charizard can do.",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Kyogre",
		image: "KyogreNextQuest5Spin.png",
		character: "Kyogre",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Absol",
		image: "AbsolNextQuest8.png",
		character: "Absol",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Meowth",
		image: "MeowthNextQuest11.png",
		character: "Meowth",
		category: "Trading Figure Game",
		content: "The Meowth figure is that of a trickster. Switch is a powerful Purple attack, swapping the places of Meowth and one of the opponent’s Pokémon. This kind of attack allows Meowth to slip by an opponent’s Pokémon sitting on the Goal, or even help trap a Pokémon with a clever surround maneuver.",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Murkrow",
		image: "MurkrowNextQuest12.png",
		character: "Murkrow",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Treecko",
		image: "TreeckoNextQuest22Spin.png",
		character: "Treecko",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Misty",
		image: "MistyNextQuest40.png",
		character: "Misty",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Red",
		image: "RedNextQuest42.png",
		character: "Red",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Feraligatr",
		image: "FeraligatrNextQuest2.png",
		character: "Feraligatr",
		category: "Trading Figure Game",
		content: "Feraligatr has highly damaging attacks. Wash Away is a stronger Purple attack — its two stars means that Wash Away beats weaker Purple attacks. It might be slow, but Feraligatr’s attacks are always strong!",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Brendan",
		image: "BrendanNextQuest41.png",
		character: "Brendan",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		ttag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "TFG Pikachu",
		image: "PikachuNextQuest18Spin.png",
		character: "Pikachu",
		category: "Trading Figure Game",
		content: "",
		company: "Kaiyodo",
		series: "Next Quest",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['tfg','kaiyodo',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Clefairy",
		image: "hasbro_clefairy_slider.jpg",
		character: "Clefairy",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Poliwhirl",
		image: "hasbro_poliwhirl_slider.jpg",
		character: "Poliwhirl",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Psyduck",
		image: "hasbro_psyduck_slider.jpg",
		character: "Psyduck",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Bulbasaur",
		image: "hasbro_bulbasaur_slider.jpg",
		character: "Bulbasaur",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Electabuzz",
		image: "hasbro_electabuzz_slider.jpg",
		character: "Electabuzz",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Sandshrew",
		image: "hasbro_sandshrew_slider.jpg",
		character: "Sandshrew",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Squirtle",
		image: "hasbro_squirtle_slider.jpg",
		character: "Squirtle",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Clefairy",
		image: "hasbro_clefairy_slider.jpg",
		character: "Clefairy",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Cubone",
		image: "hasbro_cubone_slider.jpg",
		character: "Cubone",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Ivysaur",
		image: "hasbro_ivysaur_slider.jpg",
		character: "Ivysaur",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Mewtwo",
		image: "hasbro_mewtwo_slider.jpg",
		character: "Mewtwo",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Meowth",
		image: "hasbro_meowth_slider.jpg",
		character: "Meowth",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Pidgeotto",
		image: "hasbro_pidgeotto_slider.jpg",
		character: "Pidgeotto",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Jigglypuff",
		image: "hasbro_jigglypuff_slider.jpg",
		character: "Jigglypuff",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Pikachu",
		image: "hasbro_pikachu_slider.jpg",
		character: "Pikachu",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Ekans",
		image: "hasbro_ekans_slider.jpg",
		character: "Ekans",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Slider Blastoise",
		image: "hasbro_blastoise_slider.jpg",
		character: "Blastoise",
		category: "Pre-Painted Figure",
		content: "",
		company: "Hasbro",
		series: "Sliders",
		releaseYear: 1999,
		priceUSD: 0,
		priceYen: 0,
		tag: ['slider','hasbro',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Scatterbug",
		image: "tomy_xy_scatterbug.jpg",
		character: "Scatterbug",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Spritzee",
		image: "tomy_xy_spritzee.jpg",
		character: "Spritzee",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Carbink",
		image: "tomy_carbink.jpg",
		character: "Carbink",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Flabebe",
		image: "tomy_flabebe.jpg",
		character: "Flabebe",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Chespin",
		image: "tomy_xy_chespin.jpg",
		character: "Chespin",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Chesnaught",
		image: "tomy_xy_chesnaught.jpg",
		character: "Chesnaught",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Pyroar (Male)",
		image: "tomy_xy_pyroar_m.jpg",
		character: "Pyroar (Male)",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Hydreigon",
		image: "tomy_xy_hydreigon.jpg",
		character: "Hydreigon",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Aggron",
		image: "tomy_aggron.jpg",
		character: "Aggron",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Mega Aggron",
		image: "tomy_mega_aggron.jpg",
		character: "Mega Aggron",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Helioptile",
		image: "tomy_helioptile.jpg",
		character: "Helioptile",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Gogoat",
		image: "tomy_gogoat.jpg",
		character: "Gogoat",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Quidillon",
		image: "tomy_quidillon.jpg",
		character: "Quidillon",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Fletchinder",
		image: "tomy_xy_fletchinder.jpg",
		character: "Fletchinder",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Tomy Garchomp",
		image: "tomy_xy_garchomp.jpg",
		character: "Garchomp",
		category: "Pre-Painted Figure",
		content: "",
		company: "Takara Tomy",
		series: "XY",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['takara-tomy','moncolle',''],
		comments: [],
		meta: {}
	}),
	new Item({
		author: "kellian",
		title: "Bulbasaur Beanie Plush",
		image: "hasbro_bulbasaur_beanie_plush.jpg",
		character: "Bulbasaur",
		category: "Plush",
		content: "",
		company: "Hasbro",
		series: "Beanie Plush",
		releaseYear: 0,
		priceUSD: 0,
		priceYen: 0,
		tag: ['hasbro','plush',''],
		comments: [],
		meta: {}
	})
];



var done = 0;
for(var i = 0; i < users.length; i++){
	users[i].save(function(err, result) {
		done++;
		if(done === users.length){
			submit_items();
		}
	});
}

function submit_items(){
	var done = 0;
	for(var i = 0; i < items.length; i++){
		items[i].save(function(err, result) {
			done++;
			if(done === items.length){
				exit();
			}
		});
	}
}

function exit() {mongoose.disconnect();}